import "./globals.css";

export const metadata = {
  title: "Code Extractor - Extract your code from image snippets",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
